#!/bin/bash

if test -d ~/.local/share/Trash/. 
then
    read -p "voulez vous vider la corbeille: y/n ? " reponse
    if test "$reponse" = "y"
    then
	rm -vr ~/.local/share/Trash/*
    else
	echo on efface pas alors
    fi
else
echo la poubelle est deja vide
fi