-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- INSERTION DES TROIS CATEGORIES
 
INSERT INTO Categories VALUES ( 1, 'INSTRUMENT', 'INSTRUMENT A CORDE DU MAGASIN');
INSERT INTO Categories VALUES ( 2, 'AMPLIFICATEUR', 'MATERIEL POUR AMPLIFIER LE SON D INSTRUMENT ELECTRIQUE' );
INSERT INTO Categories VALUES ( 3, 'ACCESSOIRE', 'ACCESSOIRE EN TOUT GENRE POUR JOUEUR D INSTRUMENT');
COMMIT
 
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- INSERTION DES SOUS CATEGORIES POUR CHAQUE CATEGORIES
 
-- INSERTION DES SOUCATEGORIES POUR LES ACCESSOIRES
INSERT INTO SousCategories VALUES ( 1, 'GTE', 'GUITAR ELECTRIQUE', 1 );
INSERT INTO SousCategories VALUES ( 2, 'GTEDN', 'GUITAR ELECTRIQUE A 2 NECKS', 1 );
INSERT INTO SousCategories VALUES ( 3, 'GTE7C', 'GUITAR ELECTRIQUE A 7 CORDE', 1 );
INSERT INTO SousCategories VALUES ( 4, 'GTA', 'GUITAR ACOUSTIQUE', 1 );
INSERT INTO SousCategories VALUES ( 5, 'GTF', 'GUITAR FOLK', 1 );
INSERT INTO SousCategories VALUES ( 6, 'GTAE12C', 'GUITAR ACOUSTIQUE A 12 CORDES', 1 );
INSERT INTO SousCategories VALUES ( 7, 'BE', 'BASS ELECTRIQUE', 1 );
INSERT INTO SousCategories VALUES ( 8, 'BE5C', 'BASS ELECTRIQUE A 5 CORDES', 1 );
INSERT INTO SousCategories VALUES ( 9, 'BE6C', 'BASS ELECTRIQUE A 6 CORDES', 1 );
INSERT INTO SousCategories VALUES ( 10, 'BA', 'BASS ACOUSTIQUE', 1 );
INSERT INTO SousCategories VALUES ( 11, 'UKLL', 'UKULELE', 1 );
COMMIT
 
-- INSERTION DES SOUCATEGORIES POUR LES AMPLIFICATEUR
INSERT INTO SousCategories VALUES ( 12, 'CL', 'AMPLI COMBO A LAMPE', 2 );
INSERT INTO SousCategories VALUES ( 13, 'CT', 'AMPLI COMBO A TRANSISTOR', 2 );
INSERT INTO SousCategories VALUES ( 14, 'CH', 'AMPLI COMBO HYBRIDE', 2 );
INSERT INTO SousCategories VALUES ( 15, 'TBL', 'AMPLI TETE BAFLE A LAMPE', 2 );
INSERT INTO SousCategories VALUES ( 16, 'TBT', 'AMPLI TETE BAFLE A TRANSISTOR', 2 );
INSERT INTO SousCategories VALUES ( 17, 'TBH', 'AMPLI TETE BAFLE HYBRIDE', 2 );
COMMIT
 
-- INSERTION DES SOUCATEGORIES POUR LES ACCESSOIRES
INSERT INTO SousCategories VALUES ( 18, 'SG', 'SANGLE POUR GUITARE', 3 );
INSERT INTO SousCategories VALUES ( 19, 'SB', 'SANGLE POUR BASSE', 3 );
INSERT INTO SousCategories VALUES ( 20, 'MG', 'MEDIATOR GUITARE', 3 );
INSERT INTO SousCategories VALUES ( 21, 'MB', 'MEDIATOR BASSE', 3 );
INSERT INTO SousCategories VALUES ( 22, 'PE', 'PRODUIT D ENTRETIENT', 3 );
INSERT INTO SousCategories VALUES ( 23, 'SPG', 'SUPPORT POUR GUITARE', 3 );
INSERT INTO SousCategories VALUES ( 24, 'SPB', 'SUPPORT POUR BASS', 3 );
INSERT INTO SousCategories VALUES ( 25, 'JK', 'JACK POUR INSTRUMENT ELECTRIQUE', 3 );
INSERT INTO SousCategories VALUES ( 26, 'AEA', 'ALIMENTATION ELECTRIQUE POUR AMPLI', 3 );
INSERT INTO SousCategories VALUES ( 27, 'CEG', 'CORDE EN METAL POUR GUITAR ELECTRIQUE ET FOLK', 3 );
INSERT INTO SousCategories VALUES ( 28, 'CNG', 'CORDE NYLON POUR GUITAR ACOUSTIQUE', 3 );
INSERT INTO SousCategories VALUES ( 29, 'CB', 'CORDE POUR BASS', 3 );
INSERT INTO SousCategories VALUES ( 30, 'MICG', 'MICRO POUR GUITARE ELECTRIQUE', 3 );
INSERT INTO SousCategories VALUES ( 31, 'MICB', 'MICRO POUR BASSE ELECTRIQUE ELECTRIQUE', 3 );
INSERT INTO SousCategories VALUES ( 32, 'PEE', 'PEDALE A EFFET POUR INSTRUMENT ELECTRIQUE', 3 );
COMMIT
