
package iut.jee.clients.soapservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7b02 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "helloService", targetNamespace = "http://soap.jee.iut/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.SayHelloResponse")
    public String sayHello();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "boolean", targetNamespace = "")
    @RequestWrapper(localName = "del", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.Del")
    @ResponseWrapper(localName = "delResponse", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.DelResponse")
    public Boolean del(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns iut.jee.clients.soapservices.HelloBean
     */
    @WebMethod
    @WebResult(name = "hellobean", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.UpdateResponse")
    public HelloBean update(
        @WebParam(name = "arg0", targetNamespace = "")
        HelloBean arg0);

    /**
     * 
     * @param hellobean
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.AddResponse")
    public void add(
        @WebParam(name = "hellobean", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<HelloBean> hellobean);

    /**
     * 
     * @param clientname
     * @return
     *     returns iut.jee.clients.soapservices.HelloBean
     */
    @WebMethod
    @WebResult(name = "hellobean", targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.GetResponse")
    public HelloBean get(
        @WebParam(name = "clientname", targetNamespace = "")
        String clientname);

    /**
     * 
     * @return
     *     returns java.util.List<iut.jee.clients.soapservices.HelloBean>
     */
    @WebMethod
    @WebResult(name = "hellobeanlist", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://soap.jee.iut/", className = "iut.jee.clients.soapservices.GetAllResponse")
    public List<HelloBean> getAll();

}
